### ISSUE TITLE
Admin Dashboard

### ISSUE THREAD

**Issue by BrianTum** [BuildForSDG/Team-153-Product#19]

**Comment by BrianTum** [comment]
Yes, The admin should be able to read, edit, and destroy all the data in the system.

**Comment by nyakagwafred** [comment]
> Yes, The admin should be able to read, edit, and destroy all the data in the system.

What kind of info will be displayed, like from which table columns?

**Comment by BrianTum** [comment]
roles, users, f.aid groups, f.aids, applications, reports, messages, still loading others

**Comment by BrianTum** [comment]
maybe applicants, donors and donations as well.
