### ISSUE TITLE
Setting up the base project - Laravel.

### ISSUE THREAD

**Issue by Basele** [BuildForSDG/Team-153-Product#2]
Brian Tum is assigned this

**Comment by BrianTum** [comment]
Able to git clone the repo. Laravel installed and project set for Laravel in the main directory.
Unable to git push. Check the errors below.
![git push error](https://user-images.githubusercontent.com/49562368/80927160-78428600-8da4-11ea-96a5-5df0f8ea8634.png)

**Comment by Basele** [comment]
I was able to set the new laravel installation
