### ISSUE TITLE
Generate design Mock ups

### ISSUE THREAD

**Issue by Basele** [BuildForSDG/Team-153-Product#7]
Design mock ups for the different screens .

**Comment by suhade** [comment]
![Homepge](https://user-images.githubusercontent.com/44269319/81180254-b3c08a00-8f35-11ea-8971-8a7ec05d420d.png)
![Homepage](https://user-images.githubusercontent.com/44269319/81180468-0a2dc880-8f36-11ea-8ffb-fe01c7f9dc37.png)

**Comment by Basele** [comment]
Thank you @suhade . @BrianTum  Kindly have a look at the Mock ups
